// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsYekLGSwDW8h1WUmDkXcc37asxF7e_A',
    appId: '1:505386118480:web:77eea2c3b509f85bab5055',
    messagingSenderId: '505386118480',
    projectId: 'chatapp-d351f',
    authDomain: 'chatapp-d351f.firebaseapp.com',
    storageBucket: 'chatapp-d351f.firebasestorage.app',
    measurementId: 'G-QZFJDJL7B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqBrE4VmCFvK2MyW8NsOxJUFLArtbcyaQ',
    appId: '1:505386118480:android:440db1aacb6ba62dab5055',
    messagingSenderId: '505386118480',
    projectId: 'chatapp-d351f',
    storageBucket: 'chatapp-d351f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmiJqfRLS9or7n0EUZZBYr2P5CJfZ3tUE',
    appId: '1:505386118480:ios:6698e63dc0708414ab5055',
    messagingSenderId: '505386118480',
    projectId: 'chatapp-d351f',
    storageBucket: 'chatapp-d351f.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmiJqfRLS9or7n0EUZZBYr2P5CJfZ3tUE',
    appId: '1:505386118480:ios:6698e63dc0708414ab5055',
    messagingSenderId: '505386118480',
    projectId: 'chatapp-d351f',
    storageBucket: 'chatapp-d351f.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnsYekLGSwDW8h1WUmDkXcc37asxF7e_A',
    appId: '1:505386118480:web:d06a34e27b883acdab5055',
    messagingSenderId: '505386118480',
    projectId: 'chatapp-d351f',
    authDomain: 'chatapp-d351f.firebaseapp.com',
    storageBucket: 'chatapp-d351f.firebasestorage.app',
    measurementId: 'G-9JES5PC8LL',
  );
}
